version: 2.1
jobs:
  build:
    docker:
      - image: eclipse-temurin:17.0.10_7-jdk-jammy

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: ./gradlew test --console=plain -i

      # Jacoco and codecov
      - run: ./gradlew jacocoTestReport
      - run: bash <(curl -s https://codecov.io/bash)

  build-latest:
    docker:
      - image: eclipse-temurin:17.0.10_7-jdk-jammy

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: ./gradlew test -Pmysql8 --console=plain -i

workflows:
  version: 2.0
  build-multiple:
    jobs:
      - build
      - build-latest
