version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7
        environment:
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=testdb
      - image: circleci/postgres:12.5
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=testdb
      - image: microsoft/mssql-server-linux:2017-GDR
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=jfleettestd1!
            
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Install MS cmd client
      - run: sudo apt-get install -y apt-transport-https
      - run: curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      - run: curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
      - run: sudo apt update
      - run: sudo ACCEPT_EULA=Y apt install -y mssql-tools unixodbc-dev locales-all
      - run: /opt/mssql-tools/bin/sqlcmd -H localhost -U sa -P jfleettestd1! -Q "CREATE DATABASE testdb;" 
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - run: ./gradlew test --console=plain
      
      # Jacoco and codecov
      - run: ./gradlew jacocoTestReport
      - run: bash <(curl -s https://codecov.io/bash)

  build-latest:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:8.0
        environment:
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=testdb
        #In MySql 8 local-infile is not active by default
        command: mysqld --local-infile=1
      - image: circleci/postgres:13.1
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=testdb
      - image: microsoft/mssql-server-linux:2017-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=jfleettestd1!
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Install MS cmd client
      - run: sudo apt-get install -y apt-transport-https
      - run: curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      - run: curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
      - run: sudo apt update
      - run: sudo ACCEPT_EULA=Y apt install -y mssql-tools unixodbc-dev locales-all
      - run: /opt/mssql-tools/bin/sqlcmd -H localhost -U sa -P jfleettestd1! -Q "CREATE DATABASE testdb;" 

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - run: ./gradlew test -Pmysql8 --console=plain
      
workflows:
  version: 2.0
  build-multiple:
    jobs:
      - build
      - build-latest      
